"""Add phone_number and address to ContactMessage and correct tablenames

Revision ID: 30b03fce7e66
Revises: 9033107e6c7c
Create Date: 2025-06-11 11:09:37.951331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30b03fce7e66'
down_revision = '9033107e6c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('newslettersubscription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newslettersubscription',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('subscribed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('newslettersubscription_pkey')),
    sa.UniqueConstraint('email', name=op.f('newslettersubscription_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('newsletter_subscription')
    # ### end Alembic commands ###
