"""Replace image_url with image_data and image_mimetype in BlogPost

Revision ID: 40e5ce132753
Revises: 45a9fd112097
Create Date: 2025-06-07 08:49:22.607999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e5ce132753'
down_revision = '45a9fd112097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_mimetype', sa.String(length=50), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('image_mimetype')
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###
