"""Add email to Donation

Revision ID: 45a9fd112097
Revises: 4d91be77fc8a
Create Date: 2025-06-07 08:07:06.835616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a9fd112097'
down_revision = '4d91be77fc8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.alter_column('recognition',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('paystack_transaction_ref',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('paystack_transaction_ref',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('recognition',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
