"""Add phone_number and address to ContactMessage and tablenames to models

Revision ID: 9033107e6c7c
Revises: f9f60c63d523
Create Date: 2025-06-11 10:46:32.090187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9033107e6c7c'
down_revision = 'f9f60c63d523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newslettersubscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('newsletter_subscription')
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('phone_number')

    op.create_table('newsletter_subscription',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('subscribed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('newsletter_subscription_pkey')),
    sa.UniqueConstraint('email', name=op.f('newsletter_subscription_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('newslettersubscription')
    # ### end Alembic commands ###
