"""Add Partnership model

Revision ID: dc4b7c7fdad3
Revises: 40e5ce132753
Create Date: 2025-06-07 09:27:46.130893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc4b7c7fdad3'
down_revision = '40e5ce132753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partnership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partnership')
    # ### end Alembic commands ###
